behaviors:
  CollectAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 40000000
    time_horizon: 128
    summary_freq: 20000

environment_parameters:
  collect_agent_environment:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 1.0
            max_value: 2.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 3
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 2.0
            max_value: 3.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 7
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 3.0
            max_value: 4.0
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 4.0
            max_value: 5.0
      - name: Lesson5
        completion_criteria:
          measure: reward
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 18
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 5.0
            max_value: 6.0
      - name: Lesson6
        value: 6