behaviors:
  CollectAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 128
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 40000000
    time_horizon: 160
    summary_freq: 100000

environment_parameters:
  collect_agent_environment:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 1.0
            max_value: 5.0
      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: CollectAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 5.0
            max_value: 10.0
      - name: Lesson4
        value: 10.0