behaviors:
  CollectAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 40000000
    time_horizon: 128
    summary_freq: 50000
  CollectCollectorAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 40000000
    time_horizon: 128
    summary_freq: 50000
    self_play:
      save_steps: 500000
      team_change: 1000000
      swap_steps: 200000
      window: 100
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
  CollectDisruptorAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 40000000
    time_horizon: 128
    summary_freq: 50000
    self_play:
      save_steps: 500000
      team_change: 1000000
      swap_steps: 200000
      window: 100
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0


environment_parameters:
  collect_agent_environment:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: reward
          behavior: CollectCollectorAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.95
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: CollectCollectorAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: CollectCollectorAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.85
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: CollectCollectorAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 12.35
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson4
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0